# toy time tests
name: Process PR Comment

on:
  # for POC submit/preview need a mail server
  repository_dispatch:
    types: [submit-command, preview-command]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    env:
      GIT_BASE: 2dc94da3744bfbbf145eca587a0f5ff480cc5867
      GIT_REF: 89bece5
      GITGITGADGET_REPO_OWNER: "webstech"
      GITGITGADGET_REPO_BASEOWNER: "webstech"
      GITGITGADGET_REPO_NAME: "gggmonitored"
      GITGITGADGET_MAILREPO_NAME: "gggmail"
      GITGITGADGET_MAILREPO_OWNER: "webstech"
      GITGITGADGET_MAILREPO_HOST: "github.com"
      GITGITGADGET_MAIL_AUTHOR: "gitter"
      GITGITGADGET_CONFIG: "../config.json"
      # GIT_AUTHOR_NAME: ${{ env.GITGITGADGET_MAIL_AUTHOR }}
      # GIT_AUTHOR_EMAIL: ${{ env.GITGITGADGET_MAIL_AUTHOR }}@fakehost.com

    steps:
    # install node
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    # Check out repo under sub-directory so other repos can be checked out
    # Check out gitgitgadget
    - name: gitgitgadget - Checkout
      uses: actions/checkout@v2
      with:
        repository: webstech/gitgitgadget
        path: gitgitgadget
        ref: poc

    # install gitgitgadget
    - name: gitgitgadget - Install packages
      run: npm ci
      working-directory: gitgitgadget

    # build gitgitgadget
    - name: gitgitgadget- Run build
      run: npm run build
      working-directory: gitgitgadget

    # Check out ggguser
    - name: ggguser - Checkout
      uses: actions/checkout@v2
      with:
        path: ggguser
        token: ${{ secrets.RUNNER_TOKEN }}

    # install ggguser
    - name: ggguser - Install packages
      run: npm ci
      working-directory: ggguser

    # build ggguser
    - name: ggguser - Run build
      run: npm run build
      working-directory: ggguser

    # Check out ggg supported project
    - name: gggmonitored - Checkout
      uses: actions/checkout@v2
      with:
        repository: webstech/gggmonitored
        path: gggmonitored
        token: ${{ secrets.RUNNER_TOKEN }}

    # Check out email project
    - name: gggmail - Checkout
      uses: actions/checkout@v2
      with:
        repository: webstech/gggmail
        path: gggmail
        token: ${{ secrets.RUNNER_TOKEN }}

    #
    # Finished installs and builds
    #

    # Generate a config with updates from the env
    # Not usually needed if the project can be set up with all the config values known
    - name: Generate config file
      run: |
        npm run genconfig -- -f json --file $GITGITGADGET_CONFIG
        cat $GITGITGADGET_CONFIG
      working-directory: ggguser
      env:
        config: "./build/src/model.js"

    # configure monitored repo
    - name: set monitored git config
      run: |
        git config --add gitgitgadget.smtpUser joe_user@example.com
        git config --add gitgitgadget.smtpHost localhost
        git config --add gitgitgadget.smtpPass secret
        git config --add gitgitgadget.smtpOpts "{port: 1025, secure:true, tls: {rejectUnauthorized: false}}"
        git config --add gitgitgadget.publishRemote https://github.com/$GITGITGADGET_REPO_BASEOWNER/$GITGITGADGET_REPO_NAME
        git config --add gitgitgadget.loreGitDir ../gggmail
        git config --list --local
      working-directory: ggguser
      env:
        GIT_AUTHOR_NAME: ${{ env.GITGITGADGET_MAIL_AUTHOR }}
        GIT_AUTHOR_EMAIL: ${{ env.GITGITGADGET_MAIL_AUTHOR }}@fakehost.com
        # APPTOKEN: ${{ secrets.GITGITGADGET_APPTOKEN }}

    # run innocuous misc-helper commands
    - name: misc helper process comment
      run: |
        node ../ggguser/build/mailServer/index.js --mail=../gggmail &
        sleep 2
        node build/script/misc-helper.js -g ../gggmonitored -G ../ggguser --config $GITGITGADGET_CONFIG handle-pr-comment $OWNER_ID $COMMENT_ID
        sleep 15
        kill %%
      working-directory: gitgitgadget
      env:
        GIT_AUTHOR_NAME: ${{ env.GITGITGADGET_MAIL_AUTHOR }}
        GIT_AUTHOR_EMAIL: ${{ env.GITGITGADGET_MAIL_AUTHOR }}@fakehost.com
        GIT_COMMITTER_NAME: ${{ secrets.AUTHOR }}
        GIT_COMMITTER_EMAIL: ${{ secrets.EMAIL }}
        COMMENT_ID: ${{ github.event.client_payload.github.payload.comment.id }}
        OWNER_ID: ${{ github.event.client_payload.github.payload.repository.owner.login }}
        GGG_TOKEN: ${{ secrets.RUNNER_TOKEN }}
        GIT_CONFIG_PARAMETERS: "'gitgitgadget.${{ env.GITGITGADGET_REPO_OWNER }}.githubToken=${{ secrets.RUNNER_TOKEN }}'"

    # check for emails
    - name: git log for emails
      run: |
        git branch
        git log
        git log -p -U9999 --reverse 80cb5f54834b6034be3b76dd5b66521c5310b8ac..HEAD
      working-directory: gggmail

    - name: misc helper handle new emails
      run: |
        node build/script/misc-helper.js  -g ../gggmonitored -G ../ggguser --config $GITGITGADGET_CONFIG handle-new-mails
      working-directory: gitgitgadget
      env:
        GIT_AUTHOR_NAME: ${{ env.GITGITGADGET_MAIL_AUTHOR }}
        GIT_AUTHOR_EMAIL: ${{ env.GITGITGADGET_MAIL_AUTHOR }}@fakehost.com
        GIT_COMMITTER_NAME: ${{ secrets.AUTHOR }}
        GIT_COMMITTER_EMAIL: ${{ secrets.EMAIL }}
        GGG_TOKEN: ${{ secrets.RUNNER_TOKEN }}
        GIT_CONFIG_PARAMETERS: "'gitgitgadget.${{ env.GITGITGADGET_REPO_OWNER }}.githubToken=${{ secrets.RUNNER_TOKEN }}'"

        # *********** Probably need to set this **********
        # GIT_CONFIG_PARAMETERS: 'gitgitgadget.${{ env.GITGITGADGET_REPO_BASEOWNER }}.githubtoken=${{ secrets.GITGITGADGET_APPTOKEN }}'
      # if: ${{ 1 == 0 }}
