name: Reusable workflow example

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Set token for GitHub credentials
    runs-on: ubuntu-latest
    steps:
    # Set token for GitHub credentials
    - name: Set token
      uses: actions/github-script@v6
      id: set-token
      if: ${{ 1 == 1 }}
      env:
        TOKEN: ${{ secrets.token }}
      with:
        github-token: ${{ secrets.token }}
        script: |
            const util = require('node:util');
            const execFile = util.promisify(require('node:child_process').execFile);
            const tokenConfigKey = "http.https://github.com/.extraheader";
            const basicCredential = Buffer.from(`x-access-token:${process.env.TOKEN}`, 'utf8').toString('base64');
            const tokenConfigValue = `AUTHORIZATION: basic ${basicCredential}`;
            const { stdout, stderr } = await execFile('git', ["-C", './gggmonitored', 'config', tokenConfigKey, tokenConfigValue]);
            console.log(stdout);
            console.log(stderr);
